// Shared by AI-assisted and template replies in both mailbox providers.
// Keep existing language codes stable so saved tasks remain restorable.
export const EMAIL_REPLY_LANGUAGE_OPTIONS = [
  ['en', '英语'],
  ['es', '西班牙语'],
  ['nl', '荷兰语'],
  ['de', '德语'],
  ['fr', '法语'],
  ['pt', '葡萄牙语'],
  ['pl', '波兰语'],
  ['it', '意大利语'],
  ['sv', '瑞典语'],
  ['da', '丹麦语'],
  ['no', '挪威语'],
  ['fi', '芬兰语'],
  ['is', '冰岛语'],
  ['cs', '捷克语'],
  ['sk', '斯洛伐克语'],
  ['hu', '匈牙利语'],
  ['ro', '罗马尼亚语'],
  ['bg', '保加利亚语'],
  ['el', '希腊语'],
  ['hr', '克罗地亚语'],
  ['sl', '斯洛文尼亚语'],
  ['sr', '塞尔维亚语'],
  ['bs', '波斯尼亚语'],
  ['mk', '马其顿语'],
  ['sq', '阿尔巴尼亚语'],
  ['et', '爱沙尼亚语'],
  ['lv', '拉脱维亚语'],
  ['lt', '立陶宛语'],
  ['uk', '乌克兰语'],
  ['ru', '俄语'],
  ['be', '白俄罗斯语'],
  ['ga', '爱尔兰语'],
  ['cy', '威尔士语'],
  ['mt', '马耳他语'],
  ['ca', '加泰罗尼亚语'],
  ['eu', '巴斯克语'],
  ['gl', '加利西亚语'],
  ['lb', '卢森堡语'],
  ['ja', '日语'],
] as const;
